### ISSUE TITLE
请教一下，这个env放小狐狸私钥还是放sol链的私钥

### ISSUE THREAD

**Issue by crypto-chen** [ericet/MoraSwap#1]

**Comment by ericet** [comment]
小狐狸的，这是evm链的

**Comment by crypto-chen** [comment]
是两个env吗，还是一个env，主要是改名哪里env没看懂，然后运行的时候会报split错误
![image](https://user-images.githubusercontent.com/117436136/204065306-48ed5dd7-1aaf-434f-880d-57eb5c63467b.png)

**Comment by ericet** [comment]
把.env.example改名为.env

**Comment by crypto-chen** [comment]
![image](https://user-images.githubusercontent.com/117436136/204065504-91069ec9-8bde-422b-8399-241676df59d5.png)
这个没看懂

**Comment by crypto-chen** [comment]
![image](https://user-images.githubusercontent.com/117436136/204065510-8a4cc797-d2b3-4bbf-a411-5b7a4c6e5833.png)
现在我的目录是这样子的，然后env放的是小狐狸私钥

**Comment by ericet** [comment]
代码里面的合约都没改吧，我这个脚本是8个月前写的，现在他们的合约地址都改了，需要你自己改代码里面的合约地址

**Comment by crypto-chen** [comment]
![image](https://user-images.githubusercontent.com/117436136/204065647-089f357f-40b7-42fe-8af2-04308490fa98.png)
这一串吗，改哪个值呢

**Comment by ericet** [comment]
嗯，这些合约要改。自己找找现在的合约地址改改。

**Comment by crypto-chen** [comment]
ok，谢谢，前面的key值是代币名称吗

**Comment by ericet** [comment]
前面2个是代币合约，后面是Router，Factory，LP，Staking的合约

**Comment by crypto-chen** [comment]
好的,谢谢
